"""Add middle_name to Student and Teacher

Revision ID: 65ffaa45c968
Revises: 8a3ec31ad447
Create Date: 2023-09-04 17:55:06.949092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ffaa45c968'
down_revision: Union[str, None] = '8a3ec31ad447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('middle_name', sa.String(length=128), nullable=True))
    op.add_column('teachers', sa.Column('middle_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'middle_name')
    op.drop_column('students', 'middle_name')
    # ### end Alembic commands ###
